[project]
name = "odoo-addons-oca-iot"
version = "17.0.20240728.0"
dependencies = [
    "odoo-addon-iot_oca>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
